[registries.crates-io]
protocol = "sparse"

[build]
# target = ["x86_64-unknown-linux-musl"]
# target = ["x86_64-unknown-linux-gnu"]
# target = ["aarch64-linux-android"]
# target = ["x86_64-linux-android"]
# target = ["aarch64-apple-ios"]
# target = ["x86_64-apple-ios"]
# target = ["x86_64-pc-windows-msvc"]
# target = ["x86_64-apple-darwin"]
# target = ["x86_64-unknown-freebsd"]
# target = ["x86_64-unknown-linux-ohos"]
# target = ["x86_64-unknown-openbsd"]

#
#[target.'cfg(unix)']
#runner = 'sudo -E'

# [target.'cfg(windows)']
# runner = "powershell -Command Start-Process -Verb runAs -FilePath"